ui: mocha-bdd
browserify:
  - transform: babelify
browsers:
  - name: chrome
    version: [45, latest]
  - name: firefox
    version: [45, latest]
  - name: internet explorer
    version: [10, 11]
  - name: microsoftedge
    version: [15, latest]
  - name: safari
    version: [10]
