# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://github.com/marketplace/actions/setup-node-js-environment

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      ref:
        description: "Tag, or commit SHA to checkout (optional)"
        required: false

env:
  CI: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [24, 26]
    name: Node ${{ matrix.node }}
    steps:
      # https://github.com/actions/checkout/tree/v6.0.3
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      - name: Setup Node ${{ matrix.node }}
        # https://github.com/actions/setup-node/tree/v6.3.0
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: ${{ matrix.node }}
      - run: npm install --ignore-scripts
      - run: npm run yaml
      - run: npm run lint
      - run: npm run ci
